### ISSUE TITLE
feature suggestion: Sort bibliography by year

### ISSUE THREAD

**Issue by fburic** [joksas/hugo-simplecite#2]
Hi!
I'm integrating Hugo Simple Cite into my site and liking it so far.
I'm using the ``{{< bibliography >}}`` shortcode to list all my publications, but a reasonable option would be to sort the list by year.

So I implemented my own, by changing ``get-bibentries.html`` as below and toggling the sorting with the page parameter `sort_bib_by_year`. To my mind, sorting descending by year makes the most sense as a default, but of course this could be extended.

I'm not fluent with Hugo templates so this may be a bit roundabout. The steps are to extract the year and use it as a tag in a new collection of bib entries (trying to sort directly on the deep "date-parts" field had no effect), sort the new collection by year, then extract only the actual entries (without the tag) to feed to the output of the template, for downstream use in ``print-bibliography.html``

Here's how my ``get-bibentries.html`` looks like:

```go
{{ $bibentries := "" }}
{{ $bibliography := "" }}

{{- $pageResource := .Page.Resources.GetMatch "bib.json" -}}
{{- if $pageResource }}
{{- $constructedBibResource := printf "content/%s%s" .Page.File.Dir $pageResource.Name }}
{{- $bibfilePath := $constructedBibResource }}
{{- $bibentries = getJSON $bibfilePath -}}

{{ if .Page.Params.sort_bib_by_year }}

    {{ $tagged_entries := slice }}
    {{ range $bibentry := $bibentries }}
        {{ $tagged_entries = $tagged_entries | append
            (dict "year" (index (index (index (index $bibentry "issued") "date-parts") 0) 0)
                  "entry" $bibentry
            )
        }}
    {{ end }}

    {{ $sorted_entries := slice }}
    {{ range $entry:= sort $tagged_entries "year" "desc" }}
        {{ range $k, $v := $entry }}
            {{ if eq $k "entry" }}
                {{ $sorted_entries = $sorted_entries | append $v }}
            {{end}}
        {{ end }}
    {{ end }}

    {{ $bibliography = $sorted_entries }}

{{ else }}

    {{ $bibliography = $bibentries }}

{{ end }}


{{- else -}}
    {{- errorf "No JSON file was found: %s" .Position -}}

{{- end -}}

{{ return $bibliography }}
```

**Comment by joksas** [comment]
Thank you, this looks great!

Would you like to create a PR for this? I'll happily merge it.

Also, as you allude, it would be a good idea to make this sorting more extensible for the future. Instead of a boolean page parameter `sort_bib_by_year`, we could have a parameter `bibliography_sort`, which could take a string parameter. For now, we can add two options:
- `"file_ascending"`, which would print the entries as they are listed in `bib.json` (I haven't looked at the code for a long time, but I assume that's the current default behavior?)
- `"date_descending"`, which is the behavior you implemented.

I don't really use `{{< bibliography >}}` command personally, so I'm happy with making the latter the default (i.e. the value assumed when `bibliography_sort` is not specified).

Let me know what you think and feel free to open a PR.

**Comment by fburic** [comment]
Awesome! And the suggestion sounds great!

`"file_ascending"` indeed matches the current default, since now the code just iterates over the JSON entries as read from the file. I'll be making  `"date_descending"` the new default then, for this sort of use case.

I'll make a PR along those lines soon (aiming for tomorrow even).

Thanks for the quick feedback!

**Comment by fburic** [comment]
Hi again!
I created a PR for this. Thinking more about the first sorting option, `"json_order"` might be a better description of the behavior (`"file_ascending"` is technically accurate, I'm just worried the "ascending" might confuse users about potential sorting). What do you think?

**Comment by joksas** [comment]
Thank you! I've merged the PR and published a [new release](https://github.com/joksas/hugo-simplecite/releases/tag/v0.3).

**Comment by fburic** [comment]
My pleasure! Glad I could contribute!
